apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: docker.io/dockerforomar/micropay-payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8120
          envFrom:
            - configMapRef:
                name: db-config-payment
          env:
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_USER
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBIT_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8120
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8120
            initialDelaySeconds: 30
            periodSeconds: 10
